let ciboPreferito = 'lasagna';
let prezzo;
console.log(prezzo);
prezzo = 10;
console.log(`Il prezzo della ${ciboPreferito} è di ${prezzo} euro.`);
const ristorante = "Trattoria Bella";
console.log(ristorante + ' serve il miglior piatto di ' + ciboPreferito + '!');
let punteggio = 15;
punteggio += 5;
punteggio -= 2;
punteggio ++;
let tipoPunteggio = typeof punteggio;
console.log(`Il tipo del punteggio è: ${tipoPunteggio}`);
var variabile = true;
console.log(typeof variabile);